// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/appauth"
	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppAuthQuery is the builder for querying AppAuth entities.
type AppAuthQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppAuth
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppAuthQuery builder.
func (aaq *AppAuthQuery) Where(ps ...predicate.AppAuth) *AppAuthQuery {
	aaq.predicates = append(aaq.predicates, ps...)
	return aaq
}

// Limit adds a limit step to the query.
func (aaq *AppAuthQuery) Limit(limit int) *AppAuthQuery {
	aaq.limit = &limit
	return aaq
}

// Offset adds an offset step to the query.
func (aaq *AppAuthQuery) Offset(offset int) *AppAuthQuery {
	aaq.offset = &offset
	return aaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aaq *AppAuthQuery) Unique(unique bool) *AppAuthQuery {
	aaq.unique = &unique
	return aaq
}

// Order adds an order step to the query.
func (aaq *AppAuthQuery) Order(o ...OrderFunc) *AppAuthQuery {
	aaq.order = append(aaq.order, o...)
	return aaq
}

// First returns the first AppAuth entity from the query.
// Returns a *NotFoundError when no AppAuth was found.
func (aaq *AppAuthQuery) First(ctx context.Context) (*AppAuth, error) {
	nodes, err := aaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appauth.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aaq *AppAuthQuery) FirstX(ctx context.Context) *AppAuth {
	node, err := aaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppAuth ID from the query.
// Returns a *NotFoundError when no AppAuth ID was found.
func (aaq *AppAuthQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appauth.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aaq *AppAuthQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppAuth entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AppAuth entity is not found.
// Returns a *NotFoundError when no AppAuth entities are found.
func (aaq *AppAuthQuery) Only(ctx context.Context) (*AppAuth, error) {
	nodes, err := aaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appauth.Label}
	default:
		return nil, &NotSingularError{appauth.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aaq *AppAuthQuery) OnlyX(ctx context.Context) *AppAuth {
	node, err := aaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppAuth ID in the query.
// Returns a *NotSingularError when exactly one AppAuth ID is not found.
// Returns a *NotFoundError when no entities are found.
func (aaq *AppAuthQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = &NotSingularError{appauth.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aaq *AppAuthQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppAuths.
func (aaq *AppAuthQuery) All(ctx context.Context) ([]*AppAuth, error) {
	if err := aaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aaq *AppAuthQuery) AllX(ctx context.Context) []*AppAuth {
	nodes, err := aaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppAuth IDs.
func (aaq *AppAuthQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := aaq.Select(appauth.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aaq *AppAuthQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aaq *AppAuthQuery) Count(ctx context.Context) (int, error) {
	if err := aaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aaq *AppAuthQuery) CountX(ctx context.Context) int {
	count, err := aaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aaq *AppAuthQuery) Exist(ctx context.Context) (bool, error) {
	if err := aaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aaq *AppAuthQuery) ExistX(ctx context.Context) bool {
	exist, err := aaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppAuthQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aaq *AppAuthQuery) Clone() *AppAuthQuery {
	if aaq == nil {
		return nil
	}
	return &AppAuthQuery{
		config:     aaq.config,
		limit:      aaq.limit,
		offset:     aaq.offset,
		order:      append([]OrderFunc{}, aaq.order...),
		predicates: append([]predicate.AppAuth{}, aaq.predicates...),
		// clone intermediate query.
		sql:  aaq.sql.Clone(),
		path: aaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppAuth.Query().
//		GroupBy(appauth.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (aaq *AppAuthQuery) GroupBy(field string, fields ...string) *AppAuthGroupBy {
	group := &AppAuthGroupBy{config: aaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.AppAuth.Query().
//		Select(appauth.FieldAppID).
//		Scan(ctx, &v)
//
func (aaq *AppAuthQuery) Select(fields ...string) *AppAuthSelect {
	aaq.fields = append(aaq.fields, fields...)
	return &AppAuthSelect{AppAuthQuery: aaq}
}

func (aaq *AppAuthQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aaq.fields {
		if !appauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aaq.path != nil {
		prev, err := aaq.path(ctx)
		if err != nil {
			return err
		}
		aaq.sql = prev
	}
	return nil
}

func (aaq *AppAuthQuery) sqlAll(ctx context.Context) ([]*AppAuth, error) {
	var (
		nodes = []*AppAuth{}
		_spec = aaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AppAuth{config: aaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, aaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aaq *AppAuthQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aaq.querySpec()
	_spec.Node.Columns = aaq.fields
	if len(aaq.fields) > 0 {
		_spec.Unique = aaq.unique != nil && *aaq.unique
	}
	return sqlgraph.CountNodes(ctx, aaq.driver, _spec)
}

func (aaq *AppAuthQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aaq *AppAuthQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appauth.Table,
			Columns: appauth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appauth.FieldID,
			},
		},
		From:   aaq.sql,
		Unique: true,
	}
	if unique := aaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appauth.FieldID)
		for i := range fields {
			if fields[i] != appauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aaq *AppAuthQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aaq.driver.Dialect())
	t1 := builder.Table(appauth.Table)
	columns := aaq.fields
	if len(columns) == 0 {
		columns = appauth.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aaq.sql != nil {
		selector = aaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aaq.unique != nil && *aaq.unique {
		selector.Distinct()
	}
	for _, p := range aaq.predicates {
		p(selector)
	}
	for _, p := range aaq.order {
		p(selector)
	}
	if offset := aaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppAuthGroupBy is the group-by builder for AppAuth entities.
type AppAuthGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aagb *AppAuthGroupBy) Aggregate(fns ...AggregateFunc) *AppAuthGroupBy {
	aagb.fns = append(aagb.fns, fns...)
	return aagb
}

// Scan applies the group-by query and scans the result into the given value.
func (aagb *AppAuthGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aagb.path(ctx)
	if err != nil {
		return err
	}
	aagb.sql = query
	return aagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aagb *AppAuthGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := aagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(aagb.fields) > 1 {
		return nil, errors.New("ent: AppAuthGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := aagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aagb *AppAuthGroupBy) StringsX(ctx context.Context) []string {
	v, err := aagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aagb *AppAuthGroupBy) StringX(ctx context.Context) string {
	v, err := aagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(aagb.fields) > 1 {
		return nil, errors.New("ent: AppAuthGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := aagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aagb *AppAuthGroupBy) IntsX(ctx context.Context) []int {
	v, err := aagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aagb *AppAuthGroupBy) IntX(ctx context.Context) int {
	v, err := aagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(aagb.fields) > 1 {
		return nil, errors.New("ent: AppAuthGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := aagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aagb *AppAuthGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := aagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aagb *AppAuthGroupBy) Float64X(ctx context.Context) float64 {
	v, err := aagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(aagb.fields) > 1 {
		return nil, errors.New("ent: AppAuthGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := aagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aagb *AppAuthGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := aagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aagb *AppAuthGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aagb *AppAuthGroupBy) BoolX(ctx context.Context) bool {
	v, err := aagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aagb *AppAuthGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aagb.fields {
		if !appauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aagb *AppAuthGroupBy) sqlQuery() *sql.Selector {
	selector := aagb.sql.Select()
	aggregation := make([]string, 0, len(aagb.fns))
	for _, fn := range aagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(aagb.fields)+len(aagb.fns))
		for _, f := range aagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(aagb.fields...)...)
}

// AppAuthSelect is the builder for selecting fields of AppAuth entities.
type AppAuthSelect struct {
	*AppAuthQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aas *AppAuthSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aas.prepareQuery(ctx); err != nil {
		return err
	}
	aas.sql = aas.AppAuthQuery.sqlQuery(ctx)
	return aas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aas *AppAuthSelect) ScanX(ctx context.Context, v interface{}) {
	if err := aas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) Strings(ctx context.Context) ([]string, error) {
	if len(aas.fields) > 1 {
		return nil, errors.New("ent: AppAuthSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := aas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aas *AppAuthSelect) StringsX(ctx context.Context) []string {
	v, err := aas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aas *AppAuthSelect) StringX(ctx context.Context) string {
	v, err := aas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) Ints(ctx context.Context) ([]int, error) {
	if len(aas.fields) > 1 {
		return nil, errors.New("ent: AppAuthSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := aas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aas *AppAuthSelect) IntsX(ctx context.Context) []int {
	v, err := aas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aas *AppAuthSelect) IntX(ctx context.Context) int {
	v, err := aas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(aas.fields) > 1 {
		return nil, errors.New("ent: AppAuthSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := aas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aas *AppAuthSelect) Float64sX(ctx context.Context) []float64 {
	v, err := aas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aas *AppAuthSelect) Float64X(ctx context.Context) float64 {
	v, err := aas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(aas.fields) > 1 {
		return nil, errors.New("ent: AppAuthSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := aas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aas *AppAuthSelect) BoolsX(ctx context.Context) []bool {
	v, err := aas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (aas *AppAuthSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appauth.Label}
	default:
		err = fmt.Errorf("ent: AppAuthSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aas *AppAuthSelect) BoolX(ctx context.Context) bool {
	v, err := aas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aas *AppAuthSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aas.sql.Query()
	if err := aas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
