// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/appuserauth"
	"github.com/google/uuid"
)

// AppUserAuth is the model entity for the AppUserAuth schema.
type AppUserAuth struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Resource holds the value of the "resource" field.
	Resource string `json:"resource,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// CreateAt holds the value of the "create_at" field.
	CreateAt uint32 `json:"create_at,omitempty"`
	// UpdateAt holds the value of the "update_at" field.
	UpdateAt uint32 `json:"update_at,omitempty"`
	// DeleteAt holds the value of the "delete_at" field.
	DeleteAt uint32 `json:"delete_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppUserAuth) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case appuserauth.FieldCreateAt, appuserauth.FieldUpdateAt, appuserauth.FieldDeleteAt:
			values[i] = new(sql.NullInt64)
		case appuserauth.FieldResource, appuserauth.FieldMethod:
			values[i] = new(sql.NullString)
		case appuserauth.FieldID, appuserauth.FieldAppID, appuserauth.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AppUserAuth", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppUserAuth fields.
func (aua *AppUserAuth) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appuserauth.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				aua.ID = *value
			}
		case appuserauth.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				aua.AppID = *value
			}
		case appuserauth.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				aua.UserID = *value
			}
		case appuserauth.FieldResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource", values[i])
			} else if value.Valid {
				aua.Resource = value.String
			}
		case appuserauth.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				aua.Method = value.String
			}
		case appuserauth.FieldCreateAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				aua.CreateAt = uint32(value.Int64)
			}
		case appuserauth.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				aua.UpdateAt = uint32(value.Int64)
			}
		case appuserauth.FieldDeleteAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete_at", values[i])
			} else if value.Valid {
				aua.DeleteAt = uint32(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this AppUserAuth.
// Note that you need to call AppUserAuth.Unwrap() before calling this method if this AppUserAuth
// was returned from a transaction, and the transaction was committed or rolled back.
func (aua *AppUserAuth) Update() *AppUserAuthUpdateOne {
	return (&AppUserAuthClient{config: aua.config}).UpdateOne(aua)
}

// Unwrap unwraps the AppUserAuth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aua *AppUserAuth) Unwrap() *AppUserAuth {
	tx, ok := aua.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppUserAuth is not a transactional entity")
	}
	aua.config.driver = tx.drv
	return aua
}

// String implements the fmt.Stringer.
func (aua *AppUserAuth) String() string {
	var builder strings.Builder
	builder.WriteString("AppUserAuth(")
	builder.WriteString(fmt.Sprintf("id=%v", aua.ID))
	builder.WriteString(", app_id=")
	builder.WriteString(fmt.Sprintf("%v", aua.AppID))
	builder.WriteString(", user_id=")
	builder.WriteString(fmt.Sprintf("%v", aua.UserID))
	builder.WriteString(", resource=")
	builder.WriteString(aua.Resource)
	builder.WriteString(", method=")
	builder.WriteString(aua.Method)
	builder.WriteString(", create_at=")
	builder.WriteString(fmt.Sprintf("%v", aua.CreateAt))
	builder.WriteString(", update_at=")
	builder.WriteString(fmt.Sprintf("%v", aua.UpdateAt))
	builder.WriteString(", delete_at=")
	builder.WriteString(fmt.Sprintf("%v", aua.DeleteAt))
	builder.WriteByte(')')
	return builder.String()
}

// AppUserAuths is a parsable slice of AppUserAuth.
type AppUserAuths []*AppUserAuth

func (aua AppUserAuths) config(cfg config) {
	for _i := range aua {
		aua[_i].config = cfg
	}
}
