// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/appuserauth"
	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/predicate"
)

// AppUserAuthDelete is the builder for deleting a AppUserAuth entity.
type AppUserAuthDelete struct {
	config
	hooks    []Hook
	mutation *AppUserAuthMutation
}

// Where appends a list predicates to the AppUserAuthDelete builder.
func (auad *AppUserAuthDelete) Where(ps ...predicate.AppUserAuth) *AppUserAuthDelete {
	auad.mutation.Where(ps...)
	return auad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (auad *AppUserAuthDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(auad.hooks) == 0 {
		affected, err = auad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppUserAuthMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auad.mutation = mutation
			affected, err = auad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(auad.hooks) - 1; i >= 0; i-- {
			if auad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (auad *AppUserAuthDelete) ExecX(ctx context.Context) int {
	n, err := auad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (auad *AppUserAuthDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: appuserauth.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appuserauth.FieldID,
			},
		},
	}
	if ps := auad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, auad.driver, _spec)
}

// AppUserAuthDeleteOne is the builder for deleting a single AppUserAuth entity.
type AppUserAuthDeleteOne struct {
	auad *AppUserAuthDelete
}

// Exec executes the deletion query.
func (auado *AppUserAuthDeleteOne) Exec(ctx context.Context) error {
	n, err := auado.auad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{appuserauth.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (auado *AppUserAuthDeleteOne) ExecX(ctx context.Context) {
	auado.auad.ExecX(ctx)
}
