// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/appuserauth"
	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppUserAuthQuery is the builder for querying AppUserAuth entities.
type AppUserAuthQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppUserAuth
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppUserAuthQuery builder.
func (auaq *AppUserAuthQuery) Where(ps ...predicate.AppUserAuth) *AppUserAuthQuery {
	auaq.predicates = append(auaq.predicates, ps...)
	return auaq
}

// Limit adds a limit step to the query.
func (auaq *AppUserAuthQuery) Limit(limit int) *AppUserAuthQuery {
	auaq.limit = &limit
	return auaq
}

// Offset adds an offset step to the query.
func (auaq *AppUserAuthQuery) Offset(offset int) *AppUserAuthQuery {
	auaq.offset = &offset
	return auaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (auaq *AppUserAuthQuery) Unique(unique bool) *AppUserAuthQuery {
	auaq.unique = &unique
	return auaq
}

// Order adds an order step to the query.
func (auaq *AppUserAuthQuery) Order(o ...OrderFunc) *AppUserAuthQuery {
	auaq.order = append(auaq.order, o...)
	return auaq
}

// First returns the first AppUserAuth entity from the query.
// Returns a *NotFoundError when no AppUserAuth was found.
func (auaq *AppUserAuthQuery) First(ctx context.Context) (*AppUserAuth, error) {
	nodes, err := auaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appuserauth.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (auaq *AppUserAuthQuery) FirstX(ctx context.Context) *AppUserAuth {
	node, err := auaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppUserAuth ID from the query.
// Returns a *NotFoundError when no AppUserAuth ID was found.
func (auaq *AppUserAuthQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = auaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appuserauth.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (auaq *AppUserAuthQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := auaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppUserAuth entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AppUserAuth entity is not found.
// Returns a *NotFoundError when no AppUserAuth entities are found.
func (auaq *AppUserAuthQuery) Only(ctx context.Context) (*AppUserAuth, error) {
	nodes, err := auaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appuserauth.Label}
	default:
		return nil, &NotSingularError{appuserauth.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (auaq *AppUserAuthQuery) OnlyX(ctx context.Context) *AppUserAuth {
	node, err := auaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppUserAuth ID in the query.
// Returns a *NotSingularError when exactly one AppUserAuth ID is not found.
// Returns a *NotFoundError when no entities are found.
func (auaq *AppUserAuthQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = auaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = &NotSingularError{appuserauth.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (auaq *AppUserAuthQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := auaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppUserAuths.
func (auaq *AppUserAuthQuery) All(ctx context.Context) ([]*AppUserAuth, error) {
	if err := auaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return auaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (auaq *AppUserAuthQuery) AllX(ctx context.Context) []*AppUserAuth {
	nodes, err := auaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppUserAuth IDs.
func (auaq *AppUserAuthQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := auaq.Select(appuserauth.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (auaq *AppUserAuthQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := auaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (auaq *AppUserAuthQuery) Count(ctx context.Context) (int, error) {
	if err := auaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return auaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (auaq *AppUserAuthQuery) CountX(ctx context.Context) int {
	count, err := auaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (auaq *AppUserAuthQuery) Exist(ctx context.Context) (bool, error) {
	if err := auaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return auaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (auaq *AppUserAuthQuery) ExistX(ctx context.Context) bool {
	exist, err := auaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppUserAuthQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (auaq *AppUserAuthQuery) Clone() *AppUserAuthQuery {
	if auaq == nil {
		return nil
	}
	return &AppUserAuthQuery{
		config:     auaq.config,
		limit:      auaq.limit,
		offset:     auaq.offset,
		order:      append([]OrderFunc{}, auaq.order...),
		predicates: append([]predicate.AppUserAuth{}, auaq.predicates...),
		// clone intermediate query.
		sql:  auaq.sql.Clone(),
		path: auaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppUserAuth.Query().
//		GroupBy(appuserauth.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (auaq *AppUserAuthQuery) GroupBy(field string, fields ...string) *AppUserAuthGroupBy {
	group := &AppUserAuthGroupBy{config: auaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := auaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return auaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.AppUserAuth.Query().
//		Select(appuserauth.FieldAppID).
//		Scan(ctx, &v)
//
func (auaq *AppUserAuthQuery) Select(fields ...string) *AppUserAuthSelect {
	auaq.fields = append(auaq.fields, fields...)
	return &AppUserAuthSelect{AppUserAuthQuery: auaq}
}

func (auaq *AppUserAuthQuery) prepareQuery(ctx context.Context) error {
	for _, f := range auaq.fields {
		if !appuserauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if auaq.path != nil {
		prev, err := auaq.path(ctx)
		if err != nil {
			return err
		}
		auaq.sql = prev
	}
	return nil
}

func (auaq *AppUserAuthQuery) sqlAll(ctx context.Context) ([]*AppUserAuth, error) {
	var (
		nodes = []*AppUserAuth{}
		_spec = auaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AppUserAuth{config: auaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, auaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (auaq *AppUserAuthQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := auaq.querySpec()
	_spec.Node.Columns = auaq.fields
	if len(auaq.fields) > 0 {
		_spec.Unique = auaq.unique != nil && *auaq.unique
	}
	return sqlgraph.CountNodes(ctx, auaq.driver, _spec)
}

func (auaq *AppUserAuthQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := auaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (auaq *AppUserAuthQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appuserauth.Table,
			Columns: appuserauth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appuserauth.FieldID,
			},
		},
		From:   auaq.sql,
		Unique: true,
	}
	if unique := auaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := auaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appuserauth.FieldID)
		for i := range fields {
			if fields[i] != appuserauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := auaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := auaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := auaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := auaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (auaq *AppUserAuthQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(auaq.driver.Dialect())
	t1 := builder.Table(appuserauth.Table)
	columns := auaq.fields
	if len(columns) == 0 {
		columns = appuserauth.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if auaq.sql != nil {
		selector = auaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if auaq.unique != nil && *auaq.unique {
		selector.Distinct()
	}
	for _, p := range auaq.predicates {
		p(selector)
	}
	for _, p := range auaq.order {
		p(selector)
	}
	if offset := auaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := auaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppUserAuthGroupBy is the group-by builder for AppUserAuth entities.
type AppUserAuthGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (auagb *AppUserAuthGroupBy) Aggregate(fns ...AggregateFunc) *AppUserAuthGroupBy {
	auagb.fns = append(auagb.fns, fns...)
	return auagb
}

// Scan applies the group-by query and scans the result into the given value.
func (auagb *AppUserAuthGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := auagb.path(ctx)
	if err != nil {
		return err
	}
	auagb.sql = query
	return auagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := auagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(auagb.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := auagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) StringsX(ctx context.Context) []string {
	v, err := auagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = auagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) StringX(ctx context.Context) string {
	v, err := auagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(auagb.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := auagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) IntsX(ctx context.Context) []int {
	v, err := auagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = auagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) IntX(ctx context.Context) int {
	v, err := auagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(auagb.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := auagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := auagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = auagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) Float64X(ctx context.Context) float64 {
	v, err := auagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(auagb.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := auagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := auagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (auagb *AppUserAuthGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = auagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (auagb *AppUserAuthGroupBy) BoolX(ctx context.Context) bool {
	v, err := auagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (auagb *AppUserAuthGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range auagb.fields {
		if !appuserauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := auagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := auagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (auagb *AppUserAuthGroupBy) sqlQuery() *sql.Selector {
	selector := auagb.sql.Select()
	aggregation := make([]string, 0, len(auagb.fns))
	for _, fn := range auagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(auagb.fields)+len(auagb.fns))
		for _, f := range auagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(auagb.fields...)...)
}

// AppUserAuthSelect is the builder for selecting fields of AppUserAuth entities.
type AppUserAuthSelect struct {
	*AppUserAuthQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (auas *AppUserAuthSelect) Scan(ctx context.Context, v interface{}) error {
	if err := auas.prepareQuery(ctx); err != nil {
		return err
	}
	auas.sql = auas.AppUserAuthQuery.sqlQuery(ctx)
	return auas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (auas *AppUserAuthSelect) ScanX(ctx context.Context, v interface{}) {
	if err := auas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) Strings(ctx context.Context) ([]string, error) {
	if len(auas.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := auas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (auas *AppUserAuthSelect) StringsX(ctx context.Context) []string {
	v, err := auas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = auas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (auas *AppUserAuthSelect) StringX(ctx context.Context) string {
	v, err := auas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) Ints(ctx context.Context) ([]int, error) {
	if len(auas.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := auas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (auas *AppUserAuthSelect) IntsX(ctx context.Context) []int {
	v, err := auas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = auas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (auas *AppUserAuthSelect) IntX(ctx context.Context) int {
	v, err := auas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(auas.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := auas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (auas *AppUserAuthSelect) Float64sX(ctx context.Context) []float64 {
	v, err := auas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = auas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (auas *AppUserAuthSelect) Float64X(ctx context.Context) float64 {
	v, err := auas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(auas.fields) > 1 {
		return nil, errors.New("ent: AppUserAuthSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := auas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (auas *AppUserAuthSelect) BoolsX(ctx context.Context) []bool {
	v, err := auas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (auas *AppUserAuthSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = auas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appuserauth.Label}
	default:
		err = fmt.Errorf("ent: AppUserAuthSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (auas *AppUserAuthSelect) BoolX(ctx context.Context) bool {
	v, err := auas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (auas *AppUserAuthSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := auas.sql.Query()
	if err := auas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
