// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/migrate"
	"github.com/google/uuid"

	"github.com/NpoolPlatform/authing-gateway/pkg/db/ent/authhistory"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AuthHistory is the client for interacting with the AuthHistory builders.
	AuthHistory *AuthHistoryClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AuthHistory = NewAuthHistoryClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		AuthHistory: NewAuthHistoryClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		AuthHistory: NewAuthHistoryClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AuthHistory.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AuthHistory.Use(hooks...)
}

// AuthHistoryClient is a client for the AuthHistory schema.
type AuthHistoryClient struct {
	config
}

// NewAuthHistoryClient returns a client for the AuthHistory from the given config.
func NewAuthHistoryClient(c config) *AuthHistoryClient {
	return &AuthHistoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `authhistory.Hooks(f(g(h())))`.
func (c *AuthHistoryClient) Use(hooks ...Hook) {
	c.hooks.AuthHistory = append(c.hooks.AuthHistory, hooks...)
}

// Create returns a create builder for AuthHistory.
func (c *AuthHistoryClient) Create() *AuthHistoryCreate {
	mutation := newAuthHistoryMutation(c.config, OpCreate)
	return &AuthHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuthHistory entities.
func (c *AuthHistoryClient) CreateBulk(builders ...*AuthHistoryCreate) *AuthHistoryCreateBulk {
	return &AuthHistoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuthHistory.
func (c *AuthHistoryClient) Update() *AuthHistoryUpdate {
	mutation := newAuthHistoryMutation(c.config, OpUpdate)
	return &AuthHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuthHistoryClient) UpdateOne(ah *AuthHistory) *AuthHistoryUpdateOne {
	mutation := newAuthHistoryMutation(c.config, OpUpdateOne, withAuthHistory(ah))
	return &AuthHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuthHistoryClient) UpdateOneID(id uuid.UUID) *AuthHistoryUpdateOne {
	mutation := newAuthHistoryMutation(c.config, OpUpdateOne, withAuthHistoryID(id))
	return &AuthHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuthHistory.
func (c *AuthHistoryClient) Delete() *AuthHistoryDelete {
	mutation := newAuthHistoryMutation(c.config, OpDelete)
	return &AuthHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AuthHistoryClient) DeleteOne(ah *AuthHistory) *AuthHistoryDeleteOne {
	return c.DeleteOneID(ah.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AuthHistoryClient) DeleteOneID(id uuid.UUID) *AuthHistoryDeleteOne {
	builder := c.Delete().Where(authhistory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuthHistoryDeleteOne{builder}
}

// Query returns a query builder for AuthHistory.
func (c *AuthHistoryClient) Query() *AuthHistoryQuery {
	return &AuthHistoryQuery{
		config: c.config,
	}
}

// Get returns a AuthHistory entity by its id.
func (c *AuthHistoryClient) Get(ctx context.Context, id uuid.UUID) (*AuthHistory, error) {
	return c.Query().Where(authhistory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuthHistoryClient) GetX(ctx context.Context, id uuid.UUID) *AuthHistory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuthHistoryClient) Hooks() []Hook {
	return c.hooks.AuthHistory
}
