// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthHistory is the predicate function for authhistory builders.
type AuthHistory func(*sql.Selector)
