// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppAuth is the predicate function for appauth builders.
type AppAuth func(*sql.Selector)

// AppRoleAuth is the predicate function for approleauth builders.
type AppRoleAuth func(*sql.Selector)

// AppUserAuth is the predicate function for appuserauth builders.
type AppUserAuth func(*sql.Selector)

// AuthHistory is the predicate function for authhistory builders.
type AuthHistory func(*sql.Selector)
